/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;


public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    int i;
    Thread t;
    boolean choice;
    ArrayList<JPanel> arr;
  //  ArrayList<XChartPanel> charts;
    public Student() {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        
    }
     public Student(boolean bool) {
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        this.choice=bool;
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        stdPanel2 = new javax.swing.JPanel();
        stdPanel2.setVisible(false);
        jLabel1 = new javax.swing.JLabel();
        stdchart1 = new javax.swing.JPanel();
        stdchart1.setVisible(false);
        stdchart2 = new javax.swing.JPanel();
        stdchart2.setVisible(false);
        stdchart3 = new javax.swing.JPanel();
        stdchart3.setVisible(false);
        stdchart4 = new javax.swing.JPanel();
        stdchart4.setVisible(false);
        stdchart5 = new javax.swing.JPanel();
        stdchart5.setVisible(false);
        comchart1 = new javax.swing.JPanel();
        comchart1.setVisible(false);
        comchart2 = new javax.swing.JPanel();
        comchart2.setVisible(false);
        comchart5 = new javax.swing.JPanel();
        comchart5.setVisible(false);
        comchart6 = new javax.swing.JPanel();
        comchart6.setVisible(false);
        comchart7 = new javax.swing.JPanel();
        comchart7.setVisible(false);
        stdPanel3 = new javax.swing.JPanel();
        stdPanel3.setVisible(false);
        jLabel3 = new javax.swing.JLabel();
        stdPanel4 = new javax.swing.JPanel();
        stdPanel4.setVisible(false);
        jLabel4 = new javax.swing.JLabel();
        stdPanel5 = new javax.swing.JPanel();
        stdPanel5.setVisible(false);
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        stdPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 768));

        jLayeredPane1.setBackground(new java.awt.Color(204, 0, 204));
        jLayeredPane1.setForeground(new java.awt.Color(153, 0, 153));
        jLayeredPane1.setAutoscrolls(true);
        jLayeredPane1.setMaximumSize(new java.awt.Dimension(1366, 748));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(1366, 748));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1366, 768));

        stdPanel2.setBackground(new java.awt.Color(153, 0, 153));
        stdPanel2.setMinimumSize(new java.awt.Dimension(780, 610));
        stdPanel2.setPreferredSize(new java.awt.Dimension(800, 830));
        stdPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/Screenshot from 2018-10-15 09-39-36.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        stdPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 800, 600));

        stdchart1.setLayout(new javax.swing.BoxLayout(stdchart1, javax.swing.BoxLayout.LINE_AXIS));

        stdchart2.setLayout(new javax.swing.BoxLayout(stdchart2, javax.swing.BoxLayout.LINE_AXIS));

        stdchart3.setLayout(new javax.swing.BoxLayout(stdchart3, javax.swing.BoxLayout.LINE_AXIS));

        stdchart4.setLayout(new javax.swing.BoxLayout(stdchart4, javax.swing.BoxLayout.LINE_AXIS));

        stdchart5.setLayout(new javax.swing.BoxLayout(stdchart5, javax.swing.BoxLayout.LINE_AXIS));

        comchart1.setLayout(new javax.swing.BoxLayout(comchart1, javax.swing.BoxLayout.LINE_AXIS));

        comchart2.setLayout(new javax.swing.BoxLayout(comchart2, javax.swing.BoxLayout.LINE_AXIS));

        comchart5.setLayout(new javax.swing.BoxLayout(comchart5, javax.swing.BoxLayout.LINE_AXIS));

        comchart6.setLayout(new javax.swing.BoxLayout(comchart6, javax.swing.BoxLayout.LINE_AXIS));

        comchart7.setLayout(new javax.swing.BoxLayout(comchart7, javax.swing.BoxLayout.LINE_AXIS));

        stdPanel3.setBackground(new java.awt.Color(102, 0, 102));
        stdPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/Screenshot from 2018-10-15 09-39-45.png"))); // NOI18N
        stdPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        stdPanel4.setBackground(new java.awt.Color(102, 0, 102));
        stdPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/Screenshot from 2018-10-15 09-39-48.png"))); // NOI18N
        stdPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        stdPanel5.setBackground(new java.awt.Color(102, 0, 102));
        stdPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        stdPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/Screenshot from 2018-10-15 09-39-56.png"))); // NOI18N
        stdPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/Stop.PNG"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/play.PNG"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        stdPanel6.setBackground(new java.awt.Color(204, 204, 204));
        stdPanel6.setMinimumSize(new java.awt.Dimension(1090, 650));
        stdPanel6.setPreferredSize(new java.awt.Dimension(1090, 650));
        stdPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/finalproject/images/Screenshot (64).png"))); // NOI18N
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        stdPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jLayeredPane1.setLayer(stdPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stdchart1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stdchart2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stdchart3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stdchart4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stdchart5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(comchart1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(comchart2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(comchart5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(comchart6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(comchart7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stdPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stdPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stdPanel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(stdPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(492, 492, 492))
            .addComponent(stdPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(stdchart1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(stdchart2, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(stdchart3, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(stdchart4, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(stdchart5, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(comchart1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(comchart2, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(comchart5, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(comchart6, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(comchart7, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(stdPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(stdPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(stdPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(stdPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(stdPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(stdchart1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 68, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(stdchart2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 68, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(stdchart3, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 48, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(stdchart4, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 68, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(stdchart5, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 68, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(comchart1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 68, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(comchart2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 68, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(comchart5, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 68, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(comchart6, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 68, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(comchart7, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 68, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(stdPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 68, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(stdPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 68, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(stdPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 66, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(stdPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            animate();
            jButton1.setEnabled(false);
        } catch (IOException | SQLException ex) {
            Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        t.stop();
        new Welcome().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

        // Adding charts to slide arraylist
    private JPanel addNoOfVolumes(JPanel panel)
    {
        NoOfVolumes chart=new NoOfVolumes();
        
        try {
            JPanel temp= chart.getPanel();
            panel.add(temp);
            panel.validate();
        } catch (IOException ex) {
            Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
        }
        return panel;
        
    }
    private JPanel addNumberOfBooks(JPanel panel)
    {
        NumberOfBooks chart=new NumberOfBooks();
        
        JPanel temp= chart.getPanel();
        panel.add(temp);
        panel.validate();
        return panel;
        
    }
   
    private JPanel addUsers(JPanel panel) throws IOException
    {
         Users chart=new Users();
        
        JPanel temp= chart.getPanel();
        panel.add(temp);
        panel.validate();
        return panel;
    }
    
    private JPanel addJournalsIssuedPerYear(JPanel panel) throws IOException
    {
        JournalsIssuedPerYear chart=new JournalsIssuedPerYear();
        JPanel temp=chart.getPanel();
        panel.add(temp);
        panel.validate();
        return panel;
    }
    
      private JPanel addPeriodicalsPerYear(JPanel panel) throws IOException
    {
        PeriodicalsPerYear chart=new PeriodicalsPerYear();
        JPanel temp=chart.getPanel();
        panel.add(temp);
        panel.validate();
        return panel;
    }
      
      private JPanel addLibraryArea(JPanel panel) throws IOException
    {
        LibraryArea chart=new LibraryArea();
        JPanel temp=chart.getPanel();
        panel.add(temp);
        panel.validate();
        return panel;
    }  
        private JPanel addExpenditureOnBook(JPanel panel) throws IOException
    {
        ExpenditureOnBook chart=new ExpenditureOnBook();
        JPanel temp=chart.getPanel();
        panel.add(temp);
        panel.validate();
        return panel;
    }
             private JPanel addExpenditureDistribution(JPanel panel) throws IOException, SQLException
    {
        ExpenditureDistribution chart=new ExpenditureDistribution();
        JPanel temp=chart.getPanel();
        panel.add(temp);
        panel.validate();
        return panel;
    }
   
             
    private JPanel addLibraryExpenditurePerYear(JPanel panel) throws IOException, SQLException
    {
        LibraryExpenditurePerYear chart=new LibraryExpenditurePerYear();
        JPanel temp=chart.getPanel();
        panel.add(temp);
        panel.validate();
        return panel;
    }
      //Making the slide arraylist for students
    public ArrayList<JPanel> makeSlidesStudents() throws IOException
    {
        ArrayList<JPanel> arr=new ArrayList<>();
        
        //arr.add(stdPanel1);
        arr.add(stdPanel6);
        arr.add(stdPanel2);
        arr.add(stdPanel3);
        arr.add(stdPanel4);
        arr.add(stdPanel5);
        //arr.add(stdPanel6);
        arr.add(this.addNoOfVolumes(stdchart1));
        arr.add(this.addNumberOfBooks(stdchart2));
        arr.add(this.addJournalsIssuedPerYear(stdchart3));
        arr.add(this.addPeriodicalsPerYear(stdchart4));
        arr.add(this.addUsers(stdchart5));
        return arr;
    }
    
    
    public ArrayList<JPanel> makeSlidesCommittee() throws IOException, SQLException
    {
        ArrayList<JPanel> arr=new ArrayList<>();
        arr.add(stdPanel6);
        arr.add(this.addExpenditureDistribution(comchart1));
        arr.add(this.addExpenditureOnBook(comchart2));
        arr.add(this.addLibraryExpenditurePerYear(comchart5));
        arr.add(this.addLibraryArea(comchart6));
        arr.add(this.addUsers(comchart7));
        return arr;
    }
    //Main function for starting the slide show
    public void animate() throws IOException, SQLException
    {
        
        if(this.choice==false)
        {
            this.arr=this.makeSlidesStudents();
        }
        else if(this.choice==true)
        {
          this.arr=this.makeSlidesCommittee();
        }
        for(JPanel panel:arr){
            System.out.println(panel.toString());
        }
        int size;
        size = arr.size();
            t=new Thread(){
           
           int i=0;
            @Override
            public void run()
            {
                while(true)
                {     
                    
                    System.out.println("Working");
                    for(int j=0;j<size;j++)
                    {
                         if(j==i)
                             arr.get(j).setVisible(true);
                        else
                             arr.get(j).setVisible(false);
                    }  
                    try {
                        t.sleep(6000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    jLayeredPane1.repaint();
                    i=(++i)%size;
                    
                }
            }
        };
            t.start();
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel comchart1;
    private javax.swing.JPanel comchart2;
    private javax.swing.JPanel comchart5;
    private javax.swing.JPanel comchart6;
    private javax.swing.JPanel comchart7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel stdPanel2;
    private javax.swing.JPanel stdPanel3;
    private javax.swing.JPanel stdPanel4;
    private javax.swing.JPanel stdPanel5;
    private javax.swing.JPanel stdPanel6;
    private javax.swing.JPanel stdchart1;
    private javax.swing.JPanel stdchart2;
    private javax.swing.JPanel stdchart3;
    private javax.swing.JPanel stdchart4;
    private javax.swing.JPanel stdchart5;
    // End of variables declaration//GEN-END:variables
}
