let suggestions = [
  "Channel",
  "DevGeeks",
  "Web Development",
  "YouTube",
  "YouTuber",
  "YouTube Channel",
  "What is GSSOC'23?",
  "Developer",
  "Facebook",
  "How to conribute",
  "What is open source",
  "Designer",
  "Developer",
  "Web Designer",
  "Web Developer",
  "How to learn HTML & CSS",
  "How to learn JavaScript",
  "How to become MERN stack developer",
  "How to become Web Designer",
  "How to start a Youtube Channel",
  "What does HTML stands for?",
  "What does CSS stands for?",
  "What does JS stands for?",
];
