export const LOAD_BLOG_REQUEST = 'app/BlogPage/LOAD_BLOG_REQUEST';
export const LOAD_BLOG_SUCCESS = 'app/BlogPage/LOAD_BLOG_SUCCESS';
export const LOAD_BLOG_FAILURE = 'app/BlogPage/LOAD_BLOG_FAILURE';

export const LOAD_ARCHIVES_REQUEST = 'app/BlogPage/LOAD_ARCHIVES_REQUEST';
export const LOAD_ARCHIVES_SUCCESS = 'app/BlogPage/LOAD_ARCHIVES_SUCCESS';
export const LOAD_ARCHIVES_FAILURE = 'app/BlogPage/LOAD_ARCHIVES_FAILURE';

export const LOAD_RELATED_BLOGS_REQUEST =
  'app/BlogPage/LOAD_RELATED_BLOGS_REQUEST';
export const LOAD_RELATED_BLOGS_SUCCESS =
  'app/BlogPage/LOAD_RELATED_BLOGS_SUCCESS';
export const LOAD_RELATED_BLOGS_FAILURE =
  'app/BlogPage/LOAD_RELATED_BLOGS_FAILURE';

export const LOAD_RECENT_BLOGS_REQUEST =
  'app/BlogPage/LOAD_RECENT_BLOGS_REQUEST';
export const LOAD_RECENT_BLOGS_SUCCESS =
  'app/BlogPage/LOAD_RECENT_BLOGS_SUCCESS';
export const LOAD_RECENT_BLOGS_FAILURE =
  'app/BlogPage/LOAD_RECENT_BLOGS_FAILURE';

export const SET_ONE_VALUE = 'app/BlogPage/SET_ONE_VALUE';
export const CLEAR_ONE = 'app/BlogPage/CLEAR_ONE';

export const LOAD_BLOG_LIST_REQUEST = 'app/BlogList/LOAD_BLOG_LIST_REQUEST';
export const LOAD_BLOG_LIST_SUCCESS = 'app/BlogList/LOAD_BLOG_LIST_SUCCESS';
export const LOAD_BLOG_LIST_FAILURE = 'app/BlogList/LOAD_BLOG_LIST_FAILURE';
export const SET_PAGES_VALUE = 'app/BlogList/SET_PAGES_VALUE';
export const SET_QUERY_VALUE = 'app/BlogList/SET_QUERY_VALUE';
export const SET_SIZE_VALUE = 'app/BlogList/SET_SIZE_VALUE';
export const CLEAR_ALL = 'app/BlogList/CLEAR_ALL';

export const BY_AUTHORESS = 'app/BlogList/BY_AUTHORESS';
export const LOAD_BLOG_BY_AUTHOR_REQUEST =
  'app/BlogList/LOAD_BLOG_BY_AUTHOR_REQUEST';
export const LOAD_BLOG_BY_AUTHOR_SUCCESS =
  'app/BlogList/LOAD_BLOG_BY_AUTHOR_SUCCESS';
export const LOAD_BLOG_BY_AUTHOR_FAILURE =
  'app/BlogList/LOAD_BLOG_BY_AUTHOR_FAILURE';

export const LOAD_MORE_BLOG_BY_AUTHOR_REQUEST =
  'app/BlogList/LOAD_MORE_BLOG_BY_AUTHOR_REQUEST';
export const LOAD_MORE_BLOG_BY_AUTHOR_SUCCESS =
  'app/BlogList/LOAD_MORE_BLOG_BY_AUTHOR_SUCCESS';
export const LOAD_MORE_BLOG_BY_AUTHOR_FAILURE =
  'app/BlogList/LOAD_MORE_BLOG_BY_AUTHOR_FAILURE';

export const LOAD_BLOG_BY_TAG_REQUEST = 'app/BlogList/LOAD_BLOG_BY_TAG_REQUEST';
export const LOAD_BLOG_BY_TAG_SUCCESS = 'app/BlogList/LOAD_BLOG_BY_TAG_SUCCESS';
export const LOAD_BLOG_BY_TAG_FAILURE = 'app/BlogList/LOAD_BLOG_BY_TAG_FAILURE';

export const LOAD_MORE_BLOG_BY_TAG_REQUEST =
  'app/BlogList/LOAD_MORE_BLOG_BY_TAG_REQUEST';
export const LOAD_MORE_BLOG_BY_TAG_SUCCESS =
  'app/BlogList/LOAD_MORE_BLOG_BY_TAG_SUCCESS';
export const LOAD_MORE_BLOG_BY_TAG_FAILURE =
  'app/BlogList/LOAD_MORE_BLOG_BY_TAG_FAILURE';

export const LOAD_BLOG_DATE_REQUEST = 'app/BlogList/LOAD_BLOG_DATE_REQUEST';
export const LOAD_BLOG_DATE_SUCCESS = 'app/BlogList/LOAD_BLOG_DATE_SUCCESS';
export const LOAD_BLOG_DATE_FAILURE = 'app/BlogList/LOAD_BLOG_DATE_FAILURE';

export const LOAD_CATEGORY_REQUEST =
  'app/CategoryListingPage/LOAD_CATEGORY_REQUEST';
export const LOAD_CATEGORY_SUCCESS =
  'app/CategoryListingPage/LOAD_CATEGORY_SUCCESS';
export const LOAD_CATEGORY_FAILURE =
  'app/CategoryListingPage/LOAD_CATEGORY_FAILURE';

export const LOAD_BLOG_OF_CAT_REQUEST =
  'app/CategoryDetailPage/LOAD_BLOG_OF_CAT_REQUEST';
export const LOAD_BLOG_OF_CAT_SUCCESS =
  'app/CategoryDetailPage/LOAD_BLOG_OF_CAT_SUCCESS';
export const LOAD_BLOG_OF_CAT_FAILURE =
  'app/CategoryDetailPage/LOAD_BLOG_OF_CAT_FAILURE';

export const LOAD_MORE_BLOG_OF_CAT_REQUEST =
  'app/CategoryDetailPage/LOAD_MORE_BLOG_OF_CAT_REQUEST';
export const LOAD_MORE_BLOG_OF_CAT_SUCCESS =
  'app/CategoryDetailPage/LOAD_MORE_BLOG_OF_CAT_SUCCESS';
export const LOAD_MORE_BLOG_OF_CAT_FAILURE =
  'app/CategoryDetailPage/LOAD_MORE_BLOG_OF_CAT_FAILURE';

export const CLEAR_BLOG = 'app/CategoryDetailPage/CLEAR_BLOG';
export const CLEAR_DATA = 'app/CategoryDetailPage/CLEAR_DATA';

export const LOAD_HIGHLIGHT_REQUEST = 'app/BlogPage/LOAD_HIGHLIGHT_REQUEST';
export const LOAD_HIGHLIGHT_SUCCESS = 'app/BlogPage/LOAD_HIGHLIGHT_SUCCESS';
export const LOAD_HIGHLIGHT_FAILURE = 'app/BlogPage/LOAD_HIGHLIGHT_FAILURE';

export const LOAD_SHOWCASE_REQUEST = 'app/BlogPage/LOAD_SHOWCASE_REQUEST';
export const LOAD_SHOWCASE_SUCCESS = 'app/BlogPage/LOAD_SHOWCASE_SUCCESS';
export const LOAD_SHOWCASE_FAILURE = 'app/BlogPage/LOAD_SHOWCASE_FAILURE';

export const LOAD_TRENDING_REQUEST = 'app/BlogPage/LOAD_TRENDING_REQUEST';
export const LOAD_TRENDING_SUCCESS = 'app/BlogPage/LOAD_TRENDING_SUCCESS';
export const LOAD_TRENDING_FAILURE = 'app/BlogPage/LOAD_TRENDING_FAILURE';

export const COUNT_INCREASE = 'app/BlogPage/COUNT_INCREASE';
export const COUNT_INCREASE_SUCCESS = 'app/BlogPage/COUNT_INCREASE_SUCCESS';
export const COUNT_INCREASE_FAILURE = 'app/BlogPage/COUNT_INCREASE_FAILURE';
