/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AccApplication;

import static AccApplication.DBConnection.con;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Vector;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Asus
 */
public class Purchase extends javax.swing.JFrame {

    /**
     * Creates new form Purchase
     */
    Vector Pprice;
    Vector ID; 
    Vector Company;
    Vector City;
    ResultSet rs;
    String da;
    String i;
    String a;
    String b;
    int c;
    public void pitm()
    {
        
         try{
           Statement stm = con1.createStatement();
           rs = stm.executeQuery("select * from item");
           ID = new Vector();
           Pprice = new Vector();
           while(rs.next())
           {
               item.addItem(rs.getString(2));
               ID.addElement(rs.getInt(1));
               Pprice.addElement(rs.getInt(3));
           }
        }catch(Exception ee)
        {
            System.out.println(ee);
        }
    }
    public void Company()
    {
        try{
           Statement stm = con1.createStatement();
           rs = stm.executeQuery("select * from company");
           Company = new Vector();
           City = new Vector();
           
           while(rs.next())
           {
               company.addItem(rs.getString(2));
//               Company.addElement(rs.getString(4));
               City.addElement(rs.getString(3));
           }
        }catch(Exception ee)
        {
            System.out.println(ee);
        }
    }
        Connection con1;
    public Purchase() {
        initComponents();
        con1=DBConnection.getConn();
        pitm();
        Company();
        invoiceid();
    }
public void invoiceid()
    {
        try {
          
            Statement s = con1.createStatement();
            ResultSet rs = s.executeQuery("SELECT MAX(InvoiceNo) FROM purchase");
            rs.next();
            rs.getString("MAX(InvoiceNo)");
            if (rs.getString("MAX(InvoiceNo)") == null) {
               invno.setText("P-0000001");    
            } else {
                long id = Long.parseLong(rs.getString("MAX(InvoiceNo)").substring(2,rs.getString("MAX(InvoiceNo)").length()));
                id++;
                invno.setText("P-" + String.format("%07d", id));
            }
        } catch (Exception ex) {
            System.out.println(ex);
        }      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        invno = new javax.swing.JTextField();
        home = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        item = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ppr = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tamt = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        subtmit = new javax.swing.JButton();
        pdate = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        company = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 48)); // NOI18N
        jLabel1.setText("Purchase Form");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 13, -1, 69));

        jLabel2.setText("Purchase No.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 24));
        getContentPane().add(invno, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 239, 24));

        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(757, 13, -1, -1));

        jLabel3.setText("Item");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 40, -1));

        item.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                itemItemStateChanged(evt);
            }
        });
        getContentPane().add(item, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 173, -1));

        jLabel4.setText("Company Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, 24));

        jLabel5.setText("City");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        jLabel6.setText("Quantity");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 72, 25));

        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        getContentPane().add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 206, -1));

        jLabel7.setText("Purchase Price");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));
        getContentPane().add(ppr, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 211, -1));

        jLabel8.setText("Purchase Date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 88, -1));

        jLabel9.setText("Total amount");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 84, 25));

        tamt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamtActionPerformed(evt);
            }
        });
        getContentPane().add(tamt, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 211, -1));
        getContentPane().add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 173, -1));

        subtmit.setText("SUBMIT");
        subtmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtmitActionPerformed(evt);
            }
        });
        getContentPane().add(subtmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 434, 150, 72));

        pdate.setDateFormatString("dd-MM-yyyy");
        getContentPane().add(pdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 220, -1));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51,80));

        company.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                companyItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(company, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(489, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(company, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 810, 320));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AccApplication/purchase.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
      this.setVisible(false);
      AccSystem.main(new String[2]);
    }//GEN-LAST:event_homeActionPerformed

    private void itemItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_itemItemStateChanged
        // TODO add your handling code here:
        try{
           int x = item.getSelectedIndex();
           ppr.setText(Pprice.get(x)+"");
        }catch(Exception ee)
        {
         
        }
    }//GEN-LAST:event_itemItemStateChanged

    private void tamtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamtActionPerformed
      
    }//GEN-LAST:event_tamtActionPerformed

    private void companyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_companyItemStateChanged
        // TODO add your handling code here:
        try{
           int x = company.getSelectedIndex();
           city.setText(City.get(x)+"");
        }catch(Exception ee)
        {
           
        }
    }//GEN-LAST:event_companyItemStateChanged

    private void subtmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtmitActionPerformed

         String id =invno.getText();
         try{
         PreparedStatement ps = con1.prepareStatement("insert into purchase(InvoiceNo,item,CompanyName,City,Qty,Pprice,Pdate,Totalamt) values (?,?,?,?,?,?,?,?)");
         ps.setString(1,id);
         ps.setString(2,(String)item.getSelectedItem());
         String x = (String) item.getSelectedItem();
         ps.setString(3,(String)company.getSelectedItem());
         ps.setString(4,city.getText());
         ps.setInt(5,Integer.parseInt(qty.getText()));
         ps.setInt(6,Integer.parseInt(ppr.getText()));
         SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String theDate = dateFormat.format(pdate.getDate());
        ps.setString(7,theDate);
        a = qty.getText();
        b = ppr.getText();
        c = Integer.parseInt(a)*Integer.parseInt(b);
        tamt.setText(c+"");
        ps.setInt(8,Integer.parseInt(tamt.getText()));
        ps.executeUpdate();
        showMessageDialog(this,"Purchased");
        invoiceid();

// STOCK
         int count = 0 ;
         Statement s = con1.createStatement();
         ResultSet rs = s.executeQuery("SELECT * from stock");
         
         while(rs.next())
         {
             if(rs.getString(2).equals(x)){
                 int y = rs.getInt(3);
                 y += Integer.parseInt(a);
                 int z = rs.getInt(1);
                 PreparedStatement p = con1.prepareStatement("Update stock set Qty = ? where ID = ?");
                 p.setInt(1,y);
                 p.setInt(2,z);
                 p.executeUpdate();
                 count = 1;
                 p.close();
             }
         }
         if(count  == 0)
         {
             PreparedStatement ps1 = con1.prepareStatement("Insert into stock(Item,Qty) values(?,?)");
             ps1.setString(1,x);
             ps1.setString(2,a);
             ps1.executeUpdate();
             ps1.close();
         }
     }catch(Exception ee){
       System.out.println(ee);
     }
    }//GEN-LAST:event_subtmitActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowStateChanged

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
      this.setVisible(false);
      new AccSystem().setVisible(true);
    }//GEN-LAST:event_formWindowClosing
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField city;
    private javax.swing.JComboBox<String> company;
    private javax.swing.JButton home;
    private javax.swing.JTextField invno;
    private javax.swing.JComboBox<String> item;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser pdate;
    private javax.swing.JTextField ppr;
    private javax.swing.JTextField qty;
    private javax.swing.JButton subtmit;
    private javax.swing.JTextField tamt;
    // End of variables declaration//GEN-END:variables
}
